One more ezzolmisation typo fix
It's not that there were a lot of typos, it's that there was one large mistake and I failed to see it all at once, thus why it took three pushes to fix rather than one larger push. I guess this is irresponsible GitHub use, but I panicked at the sight of the first part of the mistake, which meant I didn't take the time to make sure I had fixed the whole thing before releasing the changes...